In [1]:
!pip install pandas
!pip install mysql-connector

In [2]:
import pandas as pd
import mysql.connector
pd.set_option('display.max_columns',None)

Copyright Jana Schaich Borg/Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)

# MySQL Exercise 4: Summarizing your Data

Last week you practiced retrieving and formatting selected subsets of raw data from individual tables in a database.  In this lesson we are going to learn how to use SQL to run calculations that summarize your data without having to output all the raw rows or entries.  These calculations will serve as building blocks for the queries that will address our business questions about how to improve Dognition test completion rates.

These are the five most common aggregate functions used to summarize information stored in tables:

<img src="https://duke.box.com/shared/static/bc3yclxtwmv8dffis09hwsvskx18u1mc.jpg" width=400 alt="AGGREGATE FUNCTIONS" />

You will use COUNT and SUM very frequently.

COUNT is the only aggregate function that can work on any type of variable.  The other four aggregate functions are only appropriate for numerical data.

All aggregate functions require you to enter either a column name or a "\*" in the parentheses after the function word.   

Let's begin by exploring the COUNT function.
    

## 1. The COUNT function

**First, load the sql library and the Dognition database, and set dognition as the default database.**

In [3]:
%load_ext sql
%sql mysql://studentuser:studentpw@localhost/dognitiondb
%sql USE dognitiondb

 * mysql://studentuser:***@localhost/dognitiondb
0 rows affected.


[]

In [4]:
mydb = mysql.connector.connect(
  host="localhost",
  user="studentuser",
  passwd="studentpw",
  database="dognitiondb"
)

The Jupyter interface conveniently tells us how many rows are in our query output, so we can compare the results of the COUNT function to the results of our SELECT function.  If you run:

```mySQL
SELECT breed
FROM dogs 
```

Jupyter tells that 35050 rows are "affected", meaning there are 35050 rows in the output of the query (although, of course, we have limited the display to only 1000 rows at a time).    

**Now try running:**

```mySQL
SELECT COUNT(breed)
FROM dogs 
```

In [5]:
pd.read_sql_query("SELECT * FROM dogs LIMIT 5", mydb)

gender birthday               breed  weight  dog_fixed  dna_tested  \
0  female     2011  Labrador Retriever      50          1           0   
1    male     2007   Shetland Sheepdog      20          1           0   
2    male     2012    Golden Retriever      70          0           1   
3    male     2011    Golden Retriever      70          0           0   
4  female     2010            Shih Tzu     190          0           0   

           created_at          updated_at dimension  exclude  breed_type  \
0 2013-02-05 03:57:19 2013-07-25 19:41:49   charmer      NaN  Pure Breed   
1 2013-02-05 15:35:09 2013-07-25 19:41:49  protodog      NaN  Pure Breed   
2 2013-02-05 17:22:56 2013-07-25 19:41:49      None      NaN  Pure Breed   
3 2013-02-05 17:40:57 2014-05-30 15:52:53      None      NaN  Pure Breed   
4 2013-02-05 18:12:28 2014-05-30 15:52:54  einstein      1.0  Pure Breed   

  breed_group                              dog_guid  \
0    Sporting  fd27b272-7144-11e5-ba71-058fbc01cf0b   
1     Herding  fd27b5ba-7144-11e5-ba71-058fbc01cf0b   
2    Sporting  fd27b6b4-7144-11e5-ba71-058fbc01cf0b   
3    Sporting  fd27b79a-7144-11e5-ba71-058fbc01cf0b   
4         Toy  fd27b86c-7144-11e5-ba71-058fbc01cf0b   

                              user_guid total_tests_completed  \
0  ce134e42-7144-11e5-ba71-058fbc01cf0b                    21   
1  ce1353d8-7144-11e5-ba71-058fbc01cf0b                    20   
2  ce135ab8-7144-11e5-ba71-058fbc01cf0b                     2   
3  ce13507c-7144-11e5-ba71-058fbc01cf0b                    11   
4  ce135e14-7144-11e5-ba71-058fbc01cf0b                    31   

     mean_iti_days mean_iti_minutes   median_iti_days median_iti_minutes  \
0      28.20107581     40609.549167    0.004687499952       6.7499999308   
1    0.41330713937      595.1622807   0.0058449074865       8.4166667806   
2  0.0091319445066      13.15000009   0.0091319445066        13.15000009   
3     56.115179398     80805.858333   0.0044328703647       6.3833333252   
4     7.7342542438     11137.326111  0.00039930554425      0.57499998372   

  time_diff_between_first_and_last_game_days  \
0                                564.0215162   
1                               7.8528356481   
2                            0.0091319445066   
3                               561.15179398   
4                               232.02762731   

  time_diff_between_first_and_last_game_minutes  
0                                  812190.98333  
1                                  11308.083333  
2                                   13.15000009  
3                                  808058.58333  
4                                  334119.78333

In [6]:
pd.read_sql_query("SELECT COUNT(breed) \
                  FROM dogs;", mydb)

COUNT(breed)
0         35050

COUNT is reporting how many rows are in the breed column in total.  COUNT should give you the same output as Jupyter's output without displaying the actual rows of data that are being aggregated.  

You can use DISTINCT (which you learned about in MySQL Exercise 3) with COUNT to count all the unique values in a column, but it must be placed inside the parentheses, immediately before the column that is being counted.  For example, to count the number of distinct breed names contained within all the entries in the breed column you could query:  

```SQL
SELECT COUNT(DISTINCT breed)
  FROM dogs
```

What if you wanted to know how many indivdual dogs successfully completed at least one test?

Since every row in the complete_tests table represents a completed test and we learned earlier that there are no NULL values in the created_at column of the complete_tests table, any non-null Dog_Guid in the complete_tests table will have completed at least one test.  When a column is included in the parentheses, null values are automatically ignored.  Therefore, you could use:

```SQL
SELECT COUNT(DISTINCT Dog_Guid)
  FROM complete_tests
```

**Question 1: Try combining this query with a WHERE clause to find how many individual dogs completed tests after March 1, 2014 (the answer should be 13,289):**

In [7]:
pd.read_sql_query("SELECT COUNT(DISTINCT Dog_Guid) \
                  FROM complete_tests \
                  WHERE created_at>'2014_03_01';", mydb)

COUNT(DISTINCT Dog_Guid)
0                     13289

You can use the "\*" in the parentheses of a COUNT function to count how many rows are in the entire table (or subtable).  There are two fundamental difference between COUNT(\*) and COUNT(column_name), though.  

The first difference is that you cannot use DISTINCT with COUNT(\*). 

**Question 2: To observe the second difference yourself first, count the number of rows in the dogs table using COUNT(\*):**    


In [8]:
pd.read_sql_query("SELECT COUNT(*) \
                  FROM dogs;", mydb)

COUNT(*)
0     35050

**Question 3: Now count the number of rows in the exclude column of the dogs table:**

In [9]:
pd.read_sql_query("SELECT COUNT(exclude) \
                  FROM dogs;", mydb)

COUNT(exclude)
0            1025

The output of the second query should return a much smaller number than the output of the first query.  That's because:

><mark> When a column is included in a count function, null values are ignored in the count. When an asterisk is included in a count function, nulls are included in the count.</mark>

This will be both useful and important to remember in future queries where you might want to use SELECT(\*) to count items in multiple groups at once.  


**Question 4: How many distinct dogs have an exclude flag in the dogs table (value will be "1")? (the answer should be 853)**

In [10]:
pd.read_sql_query("SELECT COUNT(DISTINCT dog_guid) \
                   FROM dogs      \
                   WHERE exclude=1;", mydb)

COUNT(DISTINCT dog_guid)
0                       853

## 2. The SUM Function

The fact that the output of:
```mySQL
SELECT COUNT(exclude) 
FROM dogs
```
was so much lower than:
```mySQL
SELECT COUNT(*)
FROM dogs
```

suggests that there must be many NULL values in the exclude column.  Conveniently, we can combine the SUM function with ISNULL to count exactly how many NULL values there are.  Look up "ISNULL" at this link to MySQL functions I included in an earlier lesson: 

http://www.w3resource.com/mysql/mysql-functions-and-operators.php

You will see that ISNULL is a logical function that returns a 1 for every row that has a NULL value in the specified column, and a 0 for everything else.  If we sum up the number of 1s outputted by ISNULL(exclude), then, we should get the total number of NULL values in the column.  Here's what that query would look like:

```mySQL
SELECT SUM(ISNULL(exclude))
FROM dogs
```

It might be tempting to treat SQL like a calculator and leave out the SELECT statement, but you will quickly see that doesn't work.  

><mark>*Every SQL query that extracts data from a database MUST contain a SELECT statement.*  <mark\>

**Try counting the number of NULL values in the exclude column:**
      
              
     

In [11]:
pd.read_sql_query("SELECT SUM(ISNULL(exclude)) \
                   FROM dogs      \
                   ;", mydb)

SUM(ISNULL(exclude))
0               34025.0

The output should return a value of 34,025. When you add that number to the 1025 entries that have an exclude flag, you get a total of 35,050, which is the number of rows reported by SELECT COUNT(\*) from dogs.

     
     
## 3. The AVG, MIN, and MAX Functions

AVG, MIN, and MAX all work very similarly to SUM.

During the Dognition test, customers were asked the question: "How surprising were [your dog’s name]’s choices?” after completing a test.  Users could choose any number between 1 (not surprising) to 9 (very surprising).  We could retrieve the average, minimum, and maximum rating customers gave to this question after completing the "Eye Contact Game" with the following query:

```mySQL
SELECT test_name, 
AVG(rating) AS AVG_Rating, 
MIN(rating) AS MIN_Rating, 
MAX(rating) AS MAX_Rating
FROM reviews
WHERE test_name="Eye Contact Game";
```

This would give us an output with 4 columns.  The last three columns would have titles reflecting the names inputted after the AS clauses.  Recall that if you want to title a column with a string of text that contains a space, that string will need to be enclosed in quotation marks after the AS clause in your query.
   
    
**Question 5: What is the average, minimum, and maximum ratings given to "Memory versus Pointing" game? (Your answer should be 3.5584, 0, and 9, respectively)**

In [12]:
pd.read_sql_query("SELECT * FROM reviews LIMIT 1", mydb)

rating          created_at          updated_at  \
0       0 2014-05-01 19:08:00 2014-05-01 19:08:00   

                              user_guid                              dog_guid  \
0  ce3c42ca-7144-11e5-ba71-058fbc01cf0b  ce3ac77e-7144-11e5-ba71-058fbc01cf0b   

  subcategory_name     test_name  
0          Empathy  Yawn Warm-up

In [13]:
pd.read_sql_query("SELECT test_name, \
                   AVG(rating) AS AVG_Rating, \
                   MIN(rating) AS MIN_Rating, \
                   MAX(rating) AS MAX_Rating \
                   FROM reviews      \
                   WHERE test_name='Memory versus Pointing';", mydb)

test_name  AVG_Rating  MIN_Rating  MAX_Rating
0  Memory versus Pointing      3.5584           0           9

What if you wanted the average rating for each of the 40 tests in the Reviews table?  One way to do that with the tools you know already is to write 40 separate queries like the ones you wrote above for each test, and then copy or transcribe the results into a separate table in another program like Excel to assemble all the results in one place.  That would be a very tedious and time-consuming exercise.  Fortunately, there is a very simple way to produce the results you want within one query.  That's what we will learn how to do in MySQL Exercise 5.  However, it is important that you feel comfortable with the syntax we have learned thus far before we start taking advantage of that functionality. Practice is the best way to become comfortable!


## Practice incorporating aggregate functions with everything else you've learned so far in your own queries.

**Question 6: How would you query how much time it took to complete each test provided in the exam_answers table, in minutes?  Title the column that represents this data "Duration."**  Note that the exam_answers table has over 2 million rows, so if you don't limit your output, it will take longer than usual to run this query.  (HINT: use the TIMESTAMPDIFF function described at: http://www.w3resource.com/mysql/date-and-time-functions/date-and-time-functions.php.  It might seem unkind of me to keep suggesting you look up and use new functions I haven't demonstrated for you, but I really want you to become confident that you know how to look up and use new functions when you need them!  It will give you a very competitive edge in the business world.)  


In [14]:
pd.read_sql_query("SELECT * FROM exam_answers LIMIT 1", mydb)

script_detail_id subcategory_name    test_name step_type  \
0               537      Sociability  Sociability  question   

           start_time            end_time  loop_number  \
0 2013-02-05 03:58:13 2013-10-02 20:18:06            0   

                               dog_guid  
0  fd27b272-7144-11e5-ba71-058fbc01cf0b

In [15]:
pd.read_sql_query("SELECT TIMESTAMPDIFF(minute,start_time,end_time) AS Duration \
                   FROM exam_answers      \
                   LIMIT 10;", mydb)

Duration
0    345139
1    345139
2    345139
3    345138
4    345138
5    345138
6    345138
7    345138
8    345137
9    345137

**Question 7: Include a column for Dog_Guid, start_time, and end_time in your query, and examine the output.  Do you notice anything strange?**  

In [16]:
pd.read_sql_query("SELECT dog_guid,start_time, end_time, TIMESTAMPDIFF(minute,start_time,end_time) AS Duration \
                   FROM exam_answers      \
                   LIMIT 10;", mydb)

dog_guid          start_time  \
0  fd27b272-7144-11e5-ba71-058fbc01cf0b 2013-02-05 03:58:13   
1  fd27b272-7144-11e5-ba71-058fbc01cf0b 2013-02-05 03:58:31   
2  fd27b272-7144-11e5-ba71-058fbc01cf0b 2013-02-05 03:59:03   
3  fd27b272-7144-11e5-ba71-058fbc01cf0b 2013-02-05 03:59:10   
4  fd27b272-7144-11e5-ba71-058fbc01cf0b 2013-02-05 03:59:22   
5  fd27b272-7144-11e5-ba71-058fbc01cf0b 2013-02-05 03:59:36   
6  fd27b272-7144-11e5-ba71-058fbc01cf0b 2013-02-05 03:59:41   
7  fd27b272-7144-11e5-ba71-058fbc01cf0b 2013-02-05 04:00:00   
8  fd27b272-7144-11e5-ba71-058fbc01cf0b 2013-02-05 04:00:16   
9  fd27b272-7144-11e5-ba71-058fbc01cf0b 2013-02-05 04:00:35   

             end_time  Duration  
0 2013-10-02 20:18:06    345139  
1 2013-10-02 20:18:06    345139  
2 2013-10-02 20:18:06    345139  
3 2013-10-02 20:18:06    345138  
4 2013-10-02 20:18:06    345138  
5 2013-10-02 20:18:06    345138  
6 2013-10-02 20:18:06    345138  
7 2013-10-02 20:18:06    345138  
8 2013-10-02 20:18:06    345137  
9 2013-10-02 20:18:06    345137

If you explore your output you will find that some of your calculated durations appear to be "0." In some cases, you will see many entries from the same Dog_ID with the same start time and end time.  That should be impossible.  These types of entries probably represent tests run by the Dognition team rather than real customer data.  In other cases, though, a "0" is entered in the Duration column even though the start_time and end_time are different.  This is because we instructed the function to output the time difference in minutes; unless you change your settings, it will output "0" for any time differences less than the integer 1.  If you change your function to output the time difference in seconds, the duration in most of these columns will have a non-zero number.  

**Question 8: What is the average amount of time it took customers to complete all of the tests in the exam_answers table, if you do not exclude any data (the answer will be approximately 587 minutes)?**

In [17]:
pd.read_sql_query("SELECT AVG(TIMESTAMPDIFF(minute,start_time,end_time)) AS AvgDuration \
                   FROM exam_answers      \
                   LIMIT 5;", mydb)

AvgDuration
0     586.9041

**Question 9: What is the average amount of time it took customers to complete the "Treat Warm-Up" test, according to the exam_answers table (about 165 minutes, if no data is excluded)?**

In [18]:
pd.read_sql_query("SELECT AVG(TIMESTAMPDIFF(minute,start_time,end_time)) AS AvgDuration \
                   FROM exam_answers      \
                   WHERE test_name='Treat Warm-Up' \
                   LIMIT 5;", mydb)

AvgDuration
0     164.9176

**Question 10: How many possible test names are there in the exam_answers table?**

In [19]:
pd.read_sql_query("SELECT COUNT(DISTINCT test_name) \
                   FROM exam_answers      \
                   ;", mydb)

COUNT(DISTINCT test_name)
0                         67

You should have discovered that the exam_answers table has many more test names than the completed_tests table.  It turns out that this table has information about experimental tests that Dognition has not yet made available to its customers. 
   

**Question 11: What is the minimum and maximum value in the Duration column of your query that included the data from the entire table?**

In [20]:
pd.read_sql_query("SELECT MIN(TIMESTAMPDIFF(minute,start_time,end_time)) AS MinDuration, \
                   MAX(TIMESTAMPDIFF(minute,start_time,end_time)) AS MaxDuration \
                   FROM exam_answers;", mydb)

MinDuration  MaxDuration
0         -187      1036673

The minimum Duration value is *negative*!  The end_times entered in rows with negative Duration values are earlier than the start_times.  Unless Dognition has created a time machine, that's impossible and these entries must be mistakes.  

**Question 12: How many of these negative Duration entries are there? (the answer should be 620)**

In [21]:
pd.read_sql_query("SELECT COUNT(TIMESTAMPDIFF(minute,start_time,end_time)) AS Duration\
                   FROM exam_answers \
                   WHERE TIMESTAMPDIFF(minute,start_time,end_time)<0;", mydb)

Duration
0       620

**Question 13: How would you query all the columns of all the rows that have negative durations so that you could examine whether they share any features that might give you clues about what caused the entry mistake?**

In [22]:
pd.read_sql_query("SELECT *\
                   FROM exam_answers \
                   WHERE TIMESTAMPDIFF(minute,start_time,end_time)<0;", mydb)

script_detail_id subcategory_name                   test_name step_type  \
0                  60          Empathy         Eye Contact Warm-up  question   
1                 558      Sociability                 Sociability  question   
2                 557      Sociability                 Sociability  question   
3                 574     Shy/Boldness                Shy/Boldness  question   
4                 582     Shy/Boldness                Shy/Boldness  question   
..                ...              ...                         ...       ...   
615               388           Memory            Delayed Cup Game  question   
616               475        Reasoning  Inferential Reasoning Game  question   
617               388           Memory            Delayed Cup Game  question   
618               388           Memory            Delayed Cup Game  question   
619               475        Reasoning  Inferential Reasoning Game  question   

             start_time            end_time  loop_number  \
0   2013-02-17 20:35:43 2013-02-17 20:34:43            3   
1   2013-02-18 04:25:19 2013-02-18 04:24:18            0   
2   2013-02-18 07:44:09 2013-02-18 07:43:09            0   
3   2013-02-18 07:46:14 2013-02-18 07:45:13            0   
4   2013-02-18 07:47:07 2013-02-18 07:46:06            0   
..                  ...                 ...          ...   
615 2015-09-22 01:07:03 2015-09-22 01:05:28            4   
616 2015-09-22 01:22:17 2015-09-22 01:20:42            4   
617 2015-09-27 21:23:22 2015-09-27 21:16:23            3   
618 2015-09-27 21:23:22 2015-09-27 21:16:23            3   
619 2015-09-30 00:56:04 2015-09-30 00:53:05            4   

                                 dog_guid  
0    fd3fe18a-7144-11e5-ba71-058fbc01cf0b  
1    fd3fe50e-7144-11e5-ba71-058fbc01cf0b  
2    fd3fe5ea-7144-11e5-ba71-058fbc01cf0b  
3    fd3fe5ea-7144-11e5-ba71-058fbc01cf0b  
4    fd3fe5ea-7144-11e5-ba71-058fbc01cf0b  
..                                    ...  
615                                  None  
616                                  None  
617                                  None  
618                                  None  
619  fdbc021a-7144-11e5-ba71-058fbc01cf0b  

[620 rows x 8 columns]

**Question 14: What is the average amount of time it took customers to complete all of the tests in the exam_answers table when the negative durations are excluded from your calculation (you should get 11233 minutes)?**

In [23]:
pd.read_sql_query("SELECT AVG(TIMESTAMPDIFF(minute,start_time,end_time)) AS AvgDuration\
                   FROM exam_answers \
                   WHERE TIMESTAMPDIFF(minute,start_time,end_time)>0;", mydb)

AvgDuration
0   11233.0951

You have just seen another first-hand example of how messy real-world data can be, and how easy it can be to miss the "mess" when your data sets are too large to examine thoroughly by eye.  Before continuing on to the next SQL lesson, make sure to watch the video about how you as a data analyst can practice building habits that will prevent you from being fooled by messy data.

**And, as always, feel free to practice more queries here!**